calibration:
  method: linear
  min_mz_step: 80
  min_rt_step: 50
  minimum_score: 20
  outlier_std: 3
experiment:
  file_paths: []
  fractions: []
  results_path: null
  shortnames: []
fasta:
  AL_swap: false
  KR_swap: false
  database_path: null
  fasta_block: 1000
  fasta_paths: []
  max_isoforms: 1024
  max_length: 27
  min_length: 6
  mods_fixed:
  - cC
  mods_fixed_terminal: []
  mods_fixed_terminal_prot: []
  mods_variable:
  - oxM
  mods_variable_terminal: []
  mods_variable_terminal_prot: []
  num_missed_cleavages: 2
  protease: trypsin
  pseudo_reverse: true
  save_db: true
  spectra_block: 100000
features:
  mass_importance: 100
  max_distance: 0.4
  max_gap: 2
  max_neighbors: 4
  min_hill_length: 3
  ppm_tol: 8
  smoothing: 1
general:
  find_features: true
  n_processes: 128
  ppm: true
  score: x_tandem
matching:
  match_between_runs: true
  min_match_d: 3
  min_match_p: 0.05
quantification:
  max_lfq: true
  mode: int_sum
raw:
  most_abundant: 400
  use_profile_ms1: false
search:
  calibrate: true
  calibration_std: 3
  m_offset: 30
  m_tol: 30
  min_frag_hits: 7
  parallel: true
  peptide_fdr: 0.01
  ppm: true
  protein_fdr: 0.01
  recalibration_min: 100
