FROM ubuntu:20.04

RUN apt-get update && apt-get install build-essential -y
RUN apt-get install python3-pip -y

WORKDIR /home/alphapept/
COPY . .

RUN pip install .

RUN apt-get install libgomp1 -y
RUN cp  /usr/local/lib/python3.8/dist-packages/alphapept/ext/bruker/FF/linux64/libtbb.so.2 /usr/lib/libtbb.so.2
RUN chmod 555 -R  /usr/local/lib/python3.8/dist-packages/alphapept/ext/bruker/FF/linux64/uff-cmdline2
CMD ["bash"]
