# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/contributing.ipynb (unless otherwise specified).

__all__ = ['sample_function']

# Cell
def sample_function(a_string: str, a_int: int, a_flag: bool) -> str:
    """
    Sample function that performs a sample calculation.

    Args:
        a_string: A string.
        a_int: An integer.
        a_flag: A flag.

    Returns:
        A string based on the input.

    Raises:
        ValueError: An error occured when the integer is negative.

    """