workflow:
  continue_runs: false
  create_database: true
  import_raw_data: true
  find_features: true
  search_data: true
  recalibrate_data: true
  align: false
  match: false
  lfq_quantification: true
general:
  n_processes: 60
experiment:
  results_path: null
  shortnames: []
  file_paths: []
  fractions: []
  matching_groups: []
  database_path: null
  fasta_paths: []
raw:
  n_most_abundant: 400
  use_profile_ms1: false
fasta:
  mods_fixed:
  - cC
  mods_fixed_terminal: []
  mods_variable:
  - oxM
  mods_variable_terminal: []
  mods_fixed_terminal_prot: []
  mods_variable_terminal_prot:
  - a<^
  n_missed_cleavages: 2
  pep_length_min: 7
  pep_length_max: 27
  isoforms_max: 1024
  n_modifications_max: 3
  pseudo_reverse: true
  AL_swap: false
  KR_swap: false
  protease: trypsin
  spectra_block: 100000
  fasta_block: 1000
  save_db: true
  fasta_size_max: 100
features:
  max_gap: 2
  centroid_tol: 8
  hill_length_min: 3
  hill_split_level: 1.3
  iso_split_level: 1.3
  hill_smoothing: 1
  hill_check_large: 40
  iso_charge_min: 1
  iso_charge_max: 6
  iso_n_seeds: 100
  hill_nboot_max: 300
  hill_nboot: 150
  iso_mass_range: 5
  iso_corr_min: 0.6
  map_mz_range: 1.5
  map_rt_range: 0.5
  map_mob_range: 0.3
  map_n_neighbors: 5
  search_unidentified: false
search:
  prec_tol: 30
  frag_tol: 30
  min_frag_hits: 7
  ppm: true
  calibrate: true
  calibration_std_prec: 5
  calibration_std_frag: 5
  parallel: true
  peptide_fdr: 0.01
  protein_fdr: 0.01
  recalibration_min: 100
score:
  method: random_forest
calibration:
  outlier_std: 3
  calib_n_neighbors: 100
  calib_mz_range: 20
  calib_rt_range: 0.5
  calib_mob_range: 0.3
matching:
  match_p_min: 0.05
  match_d_min: 3
  match_group_tol: 0
isobaric_label:
  label: None
  reporter_frag_tolerance: 15
  reporter_frag_tolerance_ppm: true
quantification:
  max_lfq: true
  lfq_ratio_min: 1
  mode: ms1_int_sum
