# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/00_settings.ipynb (unless otherwise specified).

__all__ = ['print_settings', 'load_settings', 'load_settings_as_template', 'save_settings']

# Cell
import yaml

def print_settings(settings):
    """
    Print a yaml settings file
    """
    print(yaml.dump(settings, default_flow_style=False))


def load_settings(path):
    """
    Load a yaml settings file
    """
    with open(path, "r") as settings_file:
        SETTINGS_LOADED = yaml.load(settings_file, Loader=yaml.FullLoader)
        return SETTINGS_LOADED


def load_settings_as_template(path):
    """
    Loads settings but removes run specific fields

    """
    settings = load_settings(path)

    for _ in ['summary','failed']:
        if _ in settings:
            settings.pop(_)

    _ = 'm_offset_calibrated'
    if _ in settings['search']:
        settings['search'].pop(_)

    return settings


def save_settings(settings, path):
    """
    Save a yaml settings file to path
    """
    with open(path, "w") as file:
        yaml.dump(settings, file, sort_keys=False)