# GitHub Actions to automatically create an installer
name: Installer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_run:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Creating installer
      run: |
        cd distribution
        create_installer.bat
