name: Performance test pyinstaller

on:
  workflow_dispatch:
jobs:
  Pyinstaller:
    runs-on: self-hosted
    steps:
      - name: Freezing code
        run: |
          conda deactivate
          cd installer\one_click_windows
          .\create_installer_windows.bat
  HeLa_Thermo_Win:
    needs: Pyinstaller
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Alphapept on Thermo
      run: |
        python test_ci.py "${{ secrets.MONGODB_PW }}" thermo_hela
  HeLa_Thermo_Win_LargeFasta:
    needs: [Pyinstaller, HeLa_Thermo_Win]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Alphapept on Thermo
      run: |
        python test_ci.py "${{ secrets.MONGODB_PW }}" thermo_hela_large_fasta
  HeLa_Thermo_Win_Modifications:
    needs: [Pyinstaller, HeLa_Thermo_Win]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Alphapept on Thermo
      run: |
        python test_ci.py "${{ secrets.MONGODB_PW }}" thermo_hela_modifications
  HeLa_Bruker_Win:
    needs: [Pyinstaller, HeLa_Thermo_Win]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Alphapept on Bruker
      run: |
        python test_ci.py "${{ secrets.MONGODB_PW }}" bruker_hela
  PXD006109:
    needs: [Pyinstaller, HeLa_Thermo_Win]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Alphapept on PXD006109
      run: |
        python test_ci.py "${{ secrets.MONGODB_PW }}" PXD006109
  PXD010012:
    needs: [Pyinstaller, HeLa_Bruker_Win]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Alphapept on PXD010012
      run: |
        python test_ci.py "${{ secrets.MONGODB_PW }}" PXD010012
