name: Performance test

on:
  workflow_dispatch:

jobs:
  Install_Alphapept:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install package
      run: |
        conda create --name alphapept python=3.8 -y
        conda activate alphapept
        pip install -e .
        pip install -r requirements.txt
        pip install pymongo
        pip install dnspython
        pip install wget
  HeLa_Thermo_Win:
    needs: Install_Alphapept
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Alphapept on Thermo
      run: |
        python test_ci.py "${{ secrets.MONGODB_PW }}" thermo [thermo_HeLa.raw] [human.fasta, e_coli.fasta, contaminants.fasta]
  HeLa_Bruker_Win:
    needs: [Install_Alphapept, HeLa_Thermo_Win]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Alphapept on Bruker
      run: |
        python test_ci.py "${{ secrets.MONGODB_PW }}" bruker [bruker_HeLa.d] [human.fasta, e_coli.fasta, contaminants.fasta]
  PXD006109:
    needs: [Install_Alphapept, HeLa_Thermo_Win]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Alphapept on PXD006109
      run: |
        python test_ci.py "${{ secrets.MONGODB_PW }}" PXD006109
