# GitHub Actions to automatically test on sample files
name: Quick Test
env:
  TMP_FOLDER: 'E:/test_dir/'

on:
  push:
    branches: [ master, develop]
  pull_request:
    branches: [ master, develop]

jobs:
  Install_Alphapept:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install package (alphapept)
      run: |
        remove-item -path "C:\Users\admin\.conda\envs\alphapept" -Force -Recurse -ErrorAction SilentlyContinue
        conda create --name alphapept python=3.8 -y
        conda activate alphapept
        pip install pip --upgrade --user
        pip install ".[stable,gui-stable]"
        pip install pymongo
        pip install dnspython
        pip install wget
    - name: Run Alphapept on Thermo (IRT_Thermo_Win)
      run: |
        conda activate alphapept
        python test_ci.py "${{ env.TMP_FOLDER }}" thermo_irt "${{ secrets.MONGODB_PW }}"
    - name: Run Alphapept on Bruker (IRT_Bruker_Win)
      run: |
        conda activate alphapept
        python test_ci.py "${{ env.TMP_FOLDER }}" bruker_irt "${{ secrets.MONGODB_PW }}"
