# GitHub Actions to automatically test on sample files
name: Quick Test
env:
  TMP_FOLDER: 'E:/test_dir/'

on:
  push:
    branches: [ master, develop]
  pull_request:
    branches: [ master, develop]

jobs:
  Install_Alphapept:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install package
      run: |
        remove-item -path "C:\ProgramData\Miniconda3\envs\alphapept" -Force -Recurse -ErrorAction SilentlyContinue
        conda create --name alphapept python=3.8 -y
        conda activate alphapept
        pip install .
        pip install pymongo
        pip install dnspython
        pip install wget
  IRT_Thermo_Win:
    needs: Install_Alphapept
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Alphapept on Thermo
      run: |
        conda activate alphapept
        python test_ci.py "${{ env.TMP_FOLDER }}" thermo_irt "${{ secrets.MONGODB_PW }}"
  IRT_Bruker_Win:
    needs: [Install_Alphapept, IRT_Thermo_Win]
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Run Alphapept on Bruker
      run: |
        conda activate alphapept
        python test_ci.py "${{ env.TMP_FOLDER }}" bruker_irt "${{ secrets.MONGODB_PW }}"
