# GitHub Actions to automatically test on sample files
name: QuickTest

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  IRT_Bruker:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install package
      run: |
        conda create --name alphapept python=3.8 -y
        conda activate alphapept
        pip install -r requirements.txt
        python setup.py install
        pip install pymongo
        pip install dnspython
    - name: Preparing Files
      run: |
        $FileName = "C:\testfolder"
        if (Test-Path $FileName) {Remove-Item -Recurse -Force $FileName}
        New-Item -Path "C:\" -Name "testfolder" -ItemType "directory"
        Copy-Item -Recurse "C:\benchmark\IRT_20652.d" -Destination "C:\testfolder\"
        Copy-Item "C:\benchmark\human.fasta" -Destination "C:\testfolder\"
        Copy-Item "C:\benchmark\contaminants.fasta" -Destination "C:\testfolder\"
    - name: Run Alphapept on Bruker
      run: |
        python test_ci.py "${{ secrets.MONGODB_PW }}" "C:\benchmark\irt_test_bruker.yaml" $(git rev-parse --short "$GITHUB_SHA") ${GITHUB_REF##*/}
