# GitHub Actions to automatically test on sample files
name: HeLa Thermo Win

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  HeLa_Thermo_Win:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install package
      run: |
        conda create --name alphapept python=3.8 -y
        conda activate alphapept
        pip install -r requirements.txt
        python setup.py install
    - name: Preparing Files
      run: |
        $FileName = "C:\testfolder"
        if (Test-Path $FileName) {
        Remove-Item $FileName –recurse
        }
        New-Item -Path "C:\" -Name "testfolder" -ItemType "directory"
        Copy-Item "C:\benchmark\HeLa_500ng.raw" -Destination "C:\testfolder\"
        Copy-Item "C:\benchmark\human.fasta" -Destination "C:\testfolder\"
        Copy-Item "C:\benchmark\contaminants.fasta" -Destination "C:\testfolder\"

    - name: Run Alphapept on Thermo
      run: |
        python -m alphapept workflow C:\benchmark\hela_test_thermo.yaml
