# GitHub Actions to automatically create an installer
name: Windows Installer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_installer_windows:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Creating installer for Windows
      run: |
        conda activate alphapept
        pip install PyInstaller 
        cd distribution
        .\create_installer.bat
